### ISSUE TITLE
Crash Upon seeing stronghold

### ISSUE THREAD

**Issue by Jollyolsport** [YUNG-GANG/YUNGs-Better-Strongholds#4] opened 2021-04-18 19:41 UTC
[latest.log](https://github.com/yungnickyoung/YUNGs-Better-Strongholds/files/6332063/latest.log)

**Comment by TelepathicGrunt** [comment] 2021-04-18 19:50
@Jollyolsport  This is not caused by better strongholds but rather is caused by my mod, repurposed structures. Please try v2.6.5 that I just released right now and see if the crash goes away

**Comment by yungnickyoung** [comment] 2021-04-19 19:19
Closing because it's not caused by my mod (pls correct me @TelepathicGrunt if it is somehow due to Better Strongholds). Try the newest version of RS.

**Closed as completed by yungnickyoung** 2021-04-19 19:19 UTC
