### ISSUE TITLE
Crash bug when re-loading

### ISSUE THREAD

**Issue by Aversethule** [YUNG-GANG/YUNGs-Better-Strongholds#49] opened 2022-02-19 06:41 UTC
Hiya, playing a single player game and exited out to main server select menu and then tried to re-enter the world.  The game crashed with the following crash report, looks like a clean-up issue maybe?

https://pastebin.com/j3Mqdm64

Thanks!

**Comment by yungnickyoung** [comment] 2022-02-19 07:00
Duplicate of #48 . Should be fixed with latest version

**Closed as completed by yungnickyoung** 2022-02-19 07:00 UTC
