### ISSUE TITLE
Server crashes upon loading the stronghold.

### ISSUE THREAD

**Issue by PredictableUser** [YUNG-GANG/YUNGs-Better-Strongholds#53] opened 2022-03-13 18:16 UTC
Full pastebin of the crash: https://paste.shockbyte.com/dovelulapekoxaqepuci
1.16.4

**Comment by yungnickyoung** [comment] 2022-05-03 18:54
Looks to be due to the Zombie Awareness mod. Duplicate of #56

**Closed as completed by yungnickyoung** 2022-05-03 18:54 UTC
